### ISSUE TITLE
Auto-Conversion from String to DateTime format

### ISSUE THREAD

**Issue by Wong12Test** [DynamicODataToSQL/DynamicODataToSQL#21]
Hi,

I have one issue on string value which contained Month Name (will auto-change to DateTime format after gone through ConvertToSql), I believe that this is incorrect by auto-changing string to DateTime format.
Kindly refer to the screenshot below for the details.

Thanks.

Regards,
Wong Wei Weng

![String with Month Name Issues](https://user-images.githubusercontent.com/120087938/207220655-45b076d8-952e-4f8c-90d1-5640b6b762ab.PNG)

**Comment by Wong12Test** [comment]
Hi, any updates on this?

**Comment by maciejpieprzyk** [comment]
Hi Wong Wei Weng, I prepared a few pull requests in September and still I don't have any response. Just letting you know.

**Comment by Wong12Test** [comment]
Hi, thanks for the updating, I wish to have the fix as soon as possible.
Thanks.

**Comment by Wong12Test** [comment]
Hi, may I know the pull requests still under pending?

**Comment by Wong12Test** [comment]
Hi, may I know which version onwards will apply this fix? As I did a testing using version 1.0.7, the issue still happen.
Thanks.

**Comment by maciejpieprzyk** [comment]
Hi @Wong12Test, this fix is already included in 1.0.7. Please check [the documentation](https://github.com/DynamicODataToSQL/DynamicODataToSQL#handling-dates-on-filter) on how to use it (there is additional parameter in the ConvertToSQL method). Hope this will help you.
