### ISSUE TITLE
ConvertToSqlFromRawSql not in v 1.0.6

### ISSUE THREAD

**Issue by koopssharp** [DynamicODataToSQL/DynamicODataToSQL#26]
### Question

Hi I see the ConvertToSqlFromRawSql method on the converter is in the master branch but not in version tag 1.0.6. Is this be accident, or just not yet released?  

I'm looking for a join table function, I guess creating a join statement and load it by using ConvertToSqlFromRawSql will work a "work a round"?

**Comment by maciejpieprzyk** [comment]
Hi @koopssharp, you are right, it is not yet released. It should be soon (hopefully next week). ConvertToSqlFromRawSql will allow you to pass any query, so it should be sufficient for your scenario.
