### ISSUE TITLE
Release of new version with SQL Kata exposed

### ISSUE THREAD

**Issue by mpfund** [DynamicODataToSQL/DynamicODataToSQL#31]
### Question

Hi, we would like to use the exported sql kata function unfortunatly the latest version is from January this year (the feature was added in june). Any plans to release a new version with this functionality added anytime soon ?

**Comment by maciejpieprzyk** [comment]
Hi @mpfund, version 1.0.8 has been released.

**Comment by mpfund** [comment]
That was fast. Thank your very much!
