### ISSUE TITLE
ETA on Support for OData IN filtering?

### ISSUE THREAD

**Issue by TommySharpNZ** [DynamicODataToSQL/DynamicODataToSQL#32]
Great library and working for us well so far!
Although wondering if/when the IN filtering option might be supported?

**Comment by Rafaeruo** [comment]
I've started working on this and will most likely open a PR in the coming days.

So far the implementation is looking really simple, although I might be overlooking possible edge cases. For common IN queries, what I currently have seems to work fine, but I have yet to write unit tests.

Given that the README explicitly states that the IN operator is not supported, I imagine the maintainers may have had a reason for this. @vaibhav-goyal, is there anything specific you think I should keep in mind or edge cases to look out for?

**Comment by vaibhav-goyal** [comment]
@Rafaeruo Thank you for your work on IN clause. I think when this library was first implemented the Odata parser/object model did not support IN clause. I can't recall any edge cases so it would be great to see the PR it might remind me why we did not support IN clause in the first place.
