### ISSUE TITLE
Upgrade package versions

### ISSUE THREAD

**Issue by Fawaaz94** [DynamicODataToSQL/DynamicODataToSQL#37]
### Describe the feature

Could we upgrade some outdated package versions in the Test project. I am using your package but its causing vulnerability issues for packages needed to be upgraded, namely:

1. system.text.regularexpressions.4.3.0 -> system.text.regularexpressions.4.3.1
2. system.net.http.4.3.0 -> system.net.http.4.3.4

**Comment by kltongmy** [comment]
We have the same problem. ![image](https://github.com/DynamicODataToSQL/DynamicODataToSQL/assets/147145287/9f6d13a2-c55b-4be8-8ccf-7101ad80da11)

**Comment by kltongmy** [comment]
@vaibhav-goyal  Reporting Vulnerabilities, Thanks!
