### ISSUE TITLE
ETA on Support for OData DateTime functions?

### ISSUE THREAD

**Issue by mzhukovs** [DynamicODataToSQL/DynamicODataToSQL#9]
### Question

Great library - thank you. Question - any progress on the the support for OData DateTime functions ? Saw it was listed in your roadmap.

**Comment by vaibhav-goyal** [comment]
@mzhukovs 
I have one gentleman who has taken on to contribute this feature to the library. I will get back to you on the progress. 
I am excited to see that you are using the library, Do you want to share how you are using the library and other than DateTime functions if other features are needed ?

**Comment by mzhukovs** [comment]
I am considering using it as a generic way to set up a fully serverless "read-only API" service over data in a data lake. i.e. if a file lands in the lake, it gets exposed as a view in SQL serverless pool, and will immediately be available via an Azure function endpoint that leverages your library to allow for OData-esque querying and retrieval over http. May not be the best performance-wise, but for most use-cases this would be quite valuable at least as a starting point.

Unlike other libraries, it appears this one does not rely on any actual connection or schema, so think it could work. Still toying with the idea, would be happy to hear if you have any thoughts on it.

**Comment by vaibhav-goyal** [comment]
@mzhukovs datetime functions added in latest version.
